all:
	gcc ex1.c -lpthread -W -o ex1.out
	gcc ex2.c -lpthread -W -o ex2.out
	gcc ex3.c -lpthread -W -o ex3.out
	gcc ex4.c -W -o ex4.out
	gcc ex5.c -W -o ex5.out

ex1:
	gcc ex1.c -lphread -W

ex2:
	gcc ex2.c -lpthread -W

ex3: 
	gcc ex3.c -lpthread -W

ex4:
	gcc ex4.c -W

ex5:
	gcc ex5.c -W

clear:
	rm -rf *~
	rm -rf *.out